### ISSUE TITLE
reorganize dataverse content into parent child 

### ISSUE THREAD

**Issue by jt14den** [ucla-data-science-center/docs#6]
Check out https://just-the-docs.github.io/just-the-docs/docs/navigation-structure/#pages-with-children. In DSC, we'll have sections. Let's start with dataverse first. This documentation is intended for user facing information we want to share.

**Comment by lawtlee** [comment]
The documentation is currently ordered in parent-child format with the docs folder containing subfolders of sections.
|-- docs
|   |-- get_started
|   |   |-- index.md  (parent page)
|   |
|   |-- faq
|   |   |-- index.md (parent page)
|   |
|   |-- policies
|   |   |-- index.md      (parent page)
|   |   |-- collection.md
|   |   |-- preservation.md
|   |   |-- tos.md
